#!/bin/bash

set -Eeo pipefail

task="$1"
stack_env="$2"

function check_env {
    if [ "$1" != "dev" ] && [ "$1" != "prod" ]; then
        echo "Usage: $0 TASK STACK-ENVIRONMENT"
        echo "STACK-ENVIRONMENT must be dev or prod"
        exit 1
    fi
}

case "${task}" in
  test)
      npm install
      npm run test
      ;;
  dojo-test)
      dojo "./tasks test"
      ;;
  build)
      npm install
      npm run build
      ;;
  dojo-build)
      dojo "./tasks build"
      ;;
  get-metrics)
      npm install
      npm run getMetrics
      ;;
  dojo-get-metrics)
      dojo "./tasks get-metrics"
      ;;
  get-metadata)
      npm install
      npm run getMetadata
      ;;
  dojo-get-metadata)
      dojo "./tasks get-metadata"
      ;;
  deploy)
      export ENVIRONMENT=${stack_env}
      check_env ${ENVIRONMENT}
      npm install
      npm run deploy
      ;;
  dojo-deploy)
      dojo "./tasks deploy ${stack_env}"
      ;;
  *)
      echo "Invalid command: '${task}'"
      exit 1
      ;;
esac

set +e
