#!/bin/bash

set -Eeo pipefail

command="$1"

case "${command}" in
  _build)
      npm install
      npm run build
      ;;
  build)
      dojo "./tasks _build"
      ;;
  _deploy)
      npm install
      npm run deploy
      ;;
  deploy)
      dojo "./tasks _deploy"
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac

set +e
