export const practiceWithOneMonthMetrics = {
  odsCode: "A12345",
  name: "GP Practice",
  metrics: [
    {
      year: 2020,
      month: 2,
      requestedTransfers: {
        requestedCount: 7,
        receivedCount: 5,
        receivedPercentOfRequested: 71.42,
        integratedWithin3DaysCount: 3,
        integratedWithin3DaysPercentOfReceived: 60.0,
        integratedWithin8DaysCount: 2,
        integratedWithin8DaysPercentOfReceived: 40.0,
        notIntegratedWithin8DaysTotal: 0,
        notIntegratedWithin8DaysPercentOfReceived: null,
        failuresTotalCount: 2,
        failuresTotalPercentOfRequested: 28.6,
        integratedCount: 5,
        integratedBeyond8DaysCount: 0,
        awaitingIntegrationCount: 0,
        technicalFailuresCount: 2,
        unclassifiedFailureCount: 0,
      },
    },
  ],
};

export const practiceWithTwoMonths = {
  odsCode: "A12346",
  name: "Second GP Practice",
  metrics: [
    {
      year: 2020,
      month: 2,
      requestedTransfers: {
        requestedCount: 22,
        receivedCount: 22,
        receivedPercentOfRequested: 100.0,
        integratedWithin3DaysCount: 5,
        integratedWithin3DaysPercentOfReceived: 22.7,
        integratedWithin8DaysCount: 6,
        integratedWithin8DaysPercentOfReceived: 27.3,
        notIntegratedWithin8DaysTotal: 11,
        notIntegratedWithin8DaysPercentOfReceived: 50,
        failuresTotalCount: 0,
        failuresTotalPercentOfRequested: null,
        integratedCount: 21,
        integratedBeyond8DaysCount: 10,
        awaitingIntegrationCount: 1,
        technicalFailuresCount: 0,
        unclassifiedFailureCount: 0,
      },
    },
    {
      year: 2020,
      month: 1,
      requestedTransfers: {
        requestedCount: 22,
        receivedCount: 22,
        receivedPercentOfRequested: 100.0,
        integratedWithin3DaysCount: 5,
        integratedWithin3DaysPercentOfReceived: 22.7,
        integratedWithin8DaysCount: 6,
        integratedWithin8DaysPercentOfReceived: 27.3,
        notIntegratedWithin8DaysTotal: 11,
        notIntegratedWithin8DaysPercentOfReceived: 50,
        failuresTotalCount: 0,
        failuresTotalPercentOfRequested: null,
        integratedCount: 21,
        integratedBeyond8DaysCount: 10,
        awaitingIntegrationCount: 1,
        technicalFailuresCount: 0,
        unclassifiedFailureCount: 0,
      },
    },
  ],
};
