#!/bin/bash

set -Eeo pipefail

task="$1"
deployment_env="$2"

function check_env {
    if [ "$1" != "dev" ] && [ "$1" != "prod" ]; then
        echo "Usage: $0 TASK DEPLOYMENT_ENVIRONMENT"
        echo "DEPLOYMENT_ENVIRONMENT must be dev or prod"
        exit 1
    fi
}

function get_bucket {
    echo "prm-service-dashboard-${deployment_env}"
}

function setup_env {
    check_env "$1"
    export GATSBY_ENV="$1"
    export DEPLOYMENT_ENV="$1"
    export DEPLOYMENT_BUCKET=$(get_bucket)
}

case "${task}" in
  canary-test)
      npm i
      npm run test
      ;;
  canary-test-e2e)
      npm i
      npm run e2e:install
      npm run test:e2e:built
      ;;
  test)
      npm ci -y
      npm run test
      ;;
  test-e2e)
      npm ci -y
      npm run e2e:install
      npm run test:e2e:built
      ;;
  canary-build)
      setup_env ${deployment_env}
      npm i --production -y
      npm run build:ci
      ;;
  build)
      setup_env ${deployment_env}
      npm ci --production -y
      npm run build:ci
      ;;
  get-stubs)
      npm ci --production -y
      npm run getStubs
      ;;
  get-metrics)
      setup_env ${deployment_env}
      npm ci --production -y
      npm run getPracticeMetrics:ci
      npm run getNationalMetrics:ci
      ;;
  deploy)
      npm ci --production -y
      npm run deploy
      ;;
  dep)
      npm ci -y
      npm run audit > audit-output.txt
      ;;
  update_package_json)
      dojo "npx npm-check-updates -u --target minor"
      ;;
  publish-docker)
      if [ -z $IMAGE_TAG ]; then
          echo "Please set IMAGE_TAG environment variable"
          exit 1
      fi
      ecr_login=$(dojo -c Dojofile-infra "./scripts/ecr-helper get-login")
      ecr_repo_uri=$(dojo -c Dojofile-infra "./scripts/ecr-helper get-repo-uri")
      dojo "npm ci -y"
      docker build -t ${ecr_repo_uri}:latest -t ${ecr_repo_uri}:${IMAGE_TAG} --build-arg BUILD_TAG=$IMAGE_TAG .
      eval $ecr_login
      docker push ${ecr_repo_uri}:${IMAGE_TAG}
      ;;
  *)
      echo "Invalid command: '${task}'"
      exit 1
      ;;
esac

set +e
