format_version: 4
pipelines:
  "prm-gp2gp-dashboard-docker":
    group: gp2gp
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build_and_publish_docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - IMAGE_TAG=$GO_PIPELINE_LABEL ./tasks publish-docker